#!/usr/bin/bash
set -euo pipefail
trap 'echo "Error en línea $LINENO. Comando: $BASH_COMMAND"' ERR
cd /

# Limpieza de archivos importados
rm -f refresh conf systemd_boot extras usuarios zsh limpiar
rm -rf fonts/
rm -f lightdm.conf 50-synaptics.conf
rm -rf Luv yay_install

echo -e "\n\033[32m¡Instalación completada con éxito!\033[0m"
