#!/usr/bin/env bash
set -euo pipefail
trap 'echo "Error en línea $LINENO. Comando: $BASH_COMMAND"' ERR
# Configurar colores
RED='\033[31m'
GREEN='\033[32m'
YELLOW='\033[33m'
NC='\033[0m'

# --- Instalación base ---
selected_kernels="selected_kernelsxyz"

# Mostrar los kernels seleccionados
echo "Kernels seleccionados: $selected_kernels"

# Instalar los paquetes base junto con los kernels seleccionados
pacstrap /mnt base linux-firmware $selected_kernels cryptsetup lvm2

# --- Generar fstab ---
echo "Generando fstab..."
genfstab -U /mnt >> /mnt/etc/fstab

echo "UUID=$(blkid -s UUID -o value /dev/sda2) /boot ext4 defaults 0 2" >> /mnt/etc/fstab

# --- Continuar configuración ---
echo "Ejecutando pre-conf..."
echo "<<==============================>>"

echo -e "\033[32m==== PRE-CONF ====\033[0m"
./scripts/pre-conf
