#!/usr/bin/env bash
set -euo pipefail
trap 'echo -e "${RED}Error en línea $LINENO. Comando: $BASH_COMMAND${NC}"' ERR

# Configurar colores
RED='\033[31m'
GREEN='\033[32m'
YELLOW='\033[33m'
BLUE='\033[34m'
MAGENTA='\033[35m'
CYAN='\033[36m'
NC='\033[0m'

# --- Instalación base ---
selected_kernels="selected_kernelsxyz"

# Mostrar los kernels seleccionados
echo -e "${CYAN}Kernels seleccionados: ${YELLOW}$selected_kernels${NC}"

# Instalar los paquetes base junto con los kernels seleccionados
echo -e "${GREEN}Instalando sistema base...${NC}"
pacstrap /mnt base linux-firmware $selected_kernels cryptsetup lvm2 neovim zsh

# --- Generar fstab ---
echo -e "${GREEN}Generando fstab...${NC}"
genfstab -U /mnt >> /mnt/etc/fstab

# --- Continuar configuración ---
echo -e "${YELLOW}Ejecutando pre-conf...${NC}"
echo -e "${MAGENTA}<<==============================>>${NC}"

echo -e "${GREEN}==== PRE-CONF ====${NC}"
./scripts/pre-conf
