#!/bin/bash

# Retorna valores originales a variables
#
set -euo pipefail
trap 'echo "Error en línea $LINENO. Comando: $BASH_COMMAND"' ERR

sed -i -E 's/^hostname="[^"]+"/hostname="temporalxyz"/' conf
sed -i -E 's/[[:space:]]root_pass="[^"]+"/[[:space:]]root_pass="tu_password_root"/' usuarios
sed -i -E 's/[[:space:]]user_pass="[^"]+"/[[:space:]]user_pass="tu_password_usuario"/' usuarios
sed -i -E 's/[[:space:]]usuario="[^"]+"/[[:space:]]usuario="usuarioxyz"/' usuarios
sed -i -E 's/^[[:space:]]+desktop_choices="[[:digit:]]"/    desktop_choices="escritorioxyz"/' extras

echo -e "\033[32m==== ZSH ====\033[0m"
./zsh
