#!/usr/bin/bash
set -euo pipefail
trap 'echo -e "${RED}Error en línea $LINENO. Comando: $BASH_COMMAND${NC}"' ERR
# Configurar colores
RED='\033[31m'
GREEN='\033[32m'
YELLOW='\033[33m'
NC='\033[0m'

readonly root_pass="tu_password_root"
readonly user_pass="tu_password_usuario"
readonly usuario="usuarioxyz"

echo -e "${GREEN}Estableciendo contraseña del usuario root...${NC}"
echo "root:$root_pass" | chpasswd

echo -e "${YELLOW}===== Crear usuario =====${NC}"
#read -rp "Nombre de Usuario: " usuario

echo -e "${GREEN}Creando usuario '$usuario' con grupos y shell bash...${NC}"
useradd -m -g users -G audio,lp,optical,storage,video,wheel,games,power,scanner -s /bin/bash "$usuario"

echo -e "${YELLOW}===== Crear contraseña para ${usuario} =====${NC}"
echo "$usuario:$user_pass" | chpasswd

echo -e "${GREEN}==== GRUB ====${NC}"
./grub
