#!/usr/bin/bash
set -euo pipefail
trap 'echo "Error en línea $LINENO. Comando: $BASH_COMMAND"' ERR
# Configurar colores
RED='\033[31m'
GREEN='\033[32m'
YELLOW='\033[33m'
NC='\033[0m'

readonly root_pass="tu_password_root"
readonly user_pass="tu_password_usuario"
readonly usuario="usuarioxyz"

echo "root:$root_pass" | chpasswd

echo "===== Crear usuario ====="
#read -rp "Nombre de Usuario: " usuario

useradd -m -g users -G audio,lp,optical,storage,video,wheel,games,power,scanner -s /bin/bash "$usuario"

echo "===== Crear contraseña para $usuario ====="
echo "$usuario:$user_pass" | chpasswd

echo -e "\033[32m==== GRUB ====\033[0m"
./grub

