#!/bin/bash
set -euo pipefail
trap 'echo "Error en línea $LINENO. Comando: $BASH_COMMAND"' ERR
USER_HOME="/home/usuarioxyz"
USER_NAME="usuarioxyz"

cd "$USER_HOME"
sudo -u "$USER_NAME" bash <<EOF
  cd ~
  git clone https://aur.archlinux.org/yay.git yay
  cd yay && makepkg -si --noconfirm
  rm -rf yay

#  yay -S --noconfirm \
#      nerd-fonts-fira-code \
#      papirus-icon-theme \
#      pop-gtk-theme \
#      tela-icon-theme \
#      zsh-theme-powerlevel10k
EOF

cd /
echo -e "\033[32m==== LIMPIAR ====\033[0m"
./limpiar
